---
# tasks file for roles
- include_tasks: download.yml
- include_tasks: unzip.yml
  when: download_file_type == "zip"
- include_tasks: rm_dup.yml
- include_tasks: mount.yml
  when: download_file_type == "dmg"
- include_tasks: app.yml
  when: installer_type == "app"
- include_tasks: unmount.yml
  when: download_file_type == "dmg"